name: TDLOG

on: [pull_request, push]

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: tdlog2324-project_TD_log
        environment-file: environment.yml
        python-version: "3.11"
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: false
    - name: List packages
      run: |
        conda list
    - name: Format with black
      if: always()
      run: |
        black --check --diff .
    - name: Lint with flake8
      if: always()
      run: |
        flake8 .
    - name: Run pytest
      if: always()
      run: |
        pytest
    - name: Run pytest with coverage
      if: always()
      run: |
        pytest --cov = game.py
